
FROM node:20-alpine AS frontend-build
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build


FROM python:3.11-slim
WORKDIR /app

ENV FLASK_APP=main.py


COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY backend/ .


COPY --from=frontend-build /app/frontend/dist /app/static

EXPOSE 5000

CMD ["bash", "-c", "flask --app main:app db upgrade && gunicorn -w 4 -b 0.0.0.0:5000 main:app"]