"""initial schema

Revision ID: 67ff7cbfbc02
Revises: 
Create Date: 2026-06-24 01:59:55.684032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ff7cbfbc02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('discrimination', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('learner',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_joined_utc', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('learner', schema=None) as batch_op:
        batch_op.create_index('idx_learner_joined', ['date_joined_utc'], unique=False)

    op.create_table('course_feature',
    sa.Column('cf_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('feature_version', sa.Text(), nullable=True),
    sa.Column('prediction_cutoff_utc', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cf_id')
    )
    with op.batch_alter_table('course_feature', schema=None) as batch_op:
        batch_op.create_index('idx_cf_course_time', ['course_id', 'calculated_at'], unique=False)
        batch_op.create_index('idx_cf_version', ['feature_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_feature_course_id'), ['course_id'], unique=False)

    op.create_table('dropout_prediction',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dropout_probability', sa.Float(), nullable=False),
    sa.Column('predicted_label', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('top_features', sa.JSON(), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('prediction_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('feature_snapshot_version', sa.Text(), nullable=True),
    sa.Column('cutoff_used_utc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['learner.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    with op.batch_alter_table('dropout_prediction', schema=None) as batch_op:
        batch_op.create_index('idx_dp_model', ['model_version'], unique=False)
        batch_op.create_index('idx_dp_user_time', ['user_id', 'prediction_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_dropout_prediction_user_id'), ['user_id'], unique=False)

    op.create_table('module',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('discrimination', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('module_id')
    )
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.create_index('idx_module_course', ['course_id'], unique=False)

    op.create_table('user_course_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('last_activity_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['learner.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.create_table('lesson',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('begin_date_utc', sa.DateTime(), nullable=True),
    sa.Column('end_date_utc', sa.DateTime(), nullable=True),
    sa.Column('soft_deadline_utc', sa.DateTime(), nullable=True),
    sa.Column('hard_deadline_utc', sa.DateTime(), nullable=True),
    sa.Column('grading_policy', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.create_index('idx_lesson_module', ['module_id'], unique=False)

    op.create_table('user_dropout_feature',
    sa.Column('cf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_try_success_rate', sa.Float(), nullable=True),
    sa.Column('avg_attempts_per_step', sa.Float(), nullable=True),
    sa.Column('std_attempts_per_step', sa.Float(), nullable=True),
    sa.Column('pct_steps_with_post_success', sa.Float(), nullable=True),
    sa.Column('avg_errors_before_success', sa.Float(), nullable=True),
    sa.Column('steps_completed', sa.Integer(), nullable=False),
    sa.Column('max_step_reached', sa.Integer(), nullable=True),
    sa.Column('last_activity_utc', sa.DateTime(), nullable=True),
    sa.Column('attempts_trend_slope', sa.Float(), nullable=True),
    sa.Column('is_sequence_escalating', sa.Boolean(), nullable=True),
    sa.Column('global_attempt_pattern', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cf_id'], ['course_feature.cf_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['learner.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cf_id', 'user_id')
    )
    with op.batch_alter_table('user_dropout_feature', schema=None) as batch_op:
        batch_op.create_index('idx_udf_cf', ['cf_id'], unique=False)
        batch_op.create_index('idx_udf_unique', ['cf_id', 'user_id'], unique=True)
        batch_op.create_index('idx_udf_user', ['user_id'], unique=False)

    op.create_table('step',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Text(), nullable=True),
    sa.Column('step_cost', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('discrimination', sa.Float(), nullable=False),
    sa.Column('submissions_count', sa.Integer(), nullable=False),
    sa.Column('successful_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.lesson_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id')
    )
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.create_index('idx_step_lesson', ['lesson_id'], unique=False)

    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('time_utc', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comment.comment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['step.step_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['learner.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index('idx_comment_parent', ['parent_comment_id'], unique=False)
        batch_op.create_index('idx_comment_step', ['step_id'], unique=False)
        batch_op.create_index('idx_comment_user', ['user_id'], unique=False)

    op.create_table('submission',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attempt_time', sa.DateTime(), nullable=True),
    sa.Column('submission_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('dataset', sa.Text(), nullable=True),
    sa.Column('clue', sa.Text(), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('reply_clear', sa.Boolean(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['step.step_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['learner.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index('idx_submission_step', ['step_id'], unique=False)
        batch_op.create_index('idx_submission_time', ['submission_time'], unique=False)
        batch_op.create_index('idx_submission_time_us', ['submission_time', 'user_id', 'step_id'], unique=False)
        batch_op.create_index('idx_submission_user', ['user_id'], unique=False)

    op.create_table('user_step_feature',
    sa.Column('cf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('first_try_correct', sa.Boolean(), nullable=True),
    sa.Column('errors_before_success', sa.Integer(), nullable=True),
    sa.Column('has_post_success_attempts', sa.Boolean(), nullable=True),
    sa.Column('attempt_sequence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cf_id'], ['course_feature.cf_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['step.step_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['learner.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cf_id', 'user_id', 'step_id')
    )
    with op.batch_alter_table('user_step_feature', schema=None) as batch_op:
        batch_op.create_index('idx_usf_cf', ['cf_id'], unique=False)
        batch_op.create_index('idx_usf_step', ['step_id'], unique=False)
        batch_op.create_index('idx_usf_unique', ['cf_id', 'user_id', 'step_id'], unique=True)
        batch_op.create_index('idx_usf_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_step_feature', schema=None) as batch_op:
        batch_op.drop_index('idx_usf_user')
        batch_op.drop_index('idx_usf_unique')
        batch_op.drop_index('idx_usf_step')
        batch_op.drop_index('idx_usf_cf')

    op.drop_table('user_step_feature')
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index('idx_submission_user')
        batch_op.drop_index('idx_submission_time_us')
        batch_op.drop_index('idx_submission_time')
        batch_op.drop_index('idx_submission_step')

    op.drop_table('submission')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_user')
        batch_op.drop_index('idx_comment_step')
        batch_op.drop_index('idx_comment_parent')

    op.drop_table('comment')
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.drop_index('idx_step_lesson')

    op.drop_table('step')
    with op.batch_alter_table('user_dropout_feature', schema=None) as batch_op:
        batch_op.drop_index('idx_udf_user')
        batch_op.drop_index('idx_udf_unique')
        batch_op.drop_index('idx_udf_cf')

    op.drop_table('user_dropout_feature')
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_index('idx_lesson_module')

    op.drop_table('lesson')
    op.drop_table('user_course_progress')
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_index('idx_module_course')

    op.drop_table('module')
    with op.batch_alter_table('dropout_prediction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dropout_prediction_user_id'))
        batch_op.drop_index('idx_dp_user_time')
        batch_op.drop_index('idx_dp_model')

    op.drop_table('dropout_prediction')
    with op.batch_alter_table('course_feature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_feature_course_id'))
        batch_op.drop_index('idx_cf_version')
        batch_op.drop_index('idx_cf_course_time')

    op.drop_table('course_feature')
    with op.batch_alter_table('learner', schema=None) as batch_op:
        batch_op.drop_index('idx_learner_joined')

    op.drop_table('learner')
    op.drop_table('course')
    op.drop_table('compute_tasks')
    # ### end Alembic commands ###
